version: '3'

services:
  db:
    image: postgres
  
  web_blog:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    command: python manage.py runserver 0:8000
    volumes:
      - ../blog:/app
    ports:
      - '8000:8000'
    depends_on:
      - db
